version: '3.8'

services:
  hablemos_db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pg_config:/etc/postgresql
    networks:
      - development
    env_file:
      - .env

  hablemos_web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn hablemosdedescentralizacion.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles
    networks:
      - development
    depends_on:
      - hablemos_db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=hablemosdedescentralizacion.settings.dev
    ports:
      - "8080:8080"

volumes:
  postgres_data:

networks:
  development:
    external: true
