version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./pg_config:/etc/postgresql
    networks:
      - default

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn hablemosdedescentralizacion.wsgi:application --bind 0.0.0.0:8080"
    volumes:
      - .:/app
      - ./staticfiles:/staticfiles
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=hablemosdedescentralizacion.settings.dev

volumes:
  postgres_data: