# Generated by Django 4.2.2 on 2023-07-14 14:48

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, unique=True, verbose_name='Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo_noticia', models.CharField(max_length=200, unique=True, verbose_name='Titulo Noticia (obligatorio)')),
                ('bajada_noticia', models.CharField(max_length=200, verbose_name='Bajada noticia(obligatorio)')),
                ('contenido_noticia', models.TextField(verbose_name='contenido Noticia (obligatorio)')),
                ('autor', models.CharField(max_length=100, verbose_name='autor (opcional)')),
                ('portada_noticia', imagekit.models.fields.ProcessedImageField(null=True, upload_to='noticias', verbose_name='Foto Portada (obligatorio)')),
                ('public', models.BooleanField(default=True)),
                ('tag_noticia', models.ManyToManyField(to='noticiasymedia.tag', verbose_name='Tag noticia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo_multimedia', models.CharField(max_length=200, unique=True, verbose_name='Titulo Multimedia (obligatorio)')),
                ('descripcion_multimedia', models.TextField(verbose_name='Descripcion')),
                ('autor', models.CharField(max_length=100, verbose_name='autor (opcional)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Url video Youtube (obligatorio)')),
                ('public', models.BooleanField(default=True)),
                ('tag_media', models.ManyToManyField(to='noticiasymedia.tag', verbose_name='Tag noticia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
