# Generated by Django 4.2.2 on 2023-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiasymedia', '0002_rename_tag_media_multimedia_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='galeria_url',
            field=models.URLField(blank=True, null=True, verbose_name='Url galeria de fotos'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='public',
            field=models.BooleanField(default=True, verbose_name='publico'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='video_url',
            field=models.URLField(null=True, verbose_name='Url video Youtube (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='bajada_noticia',
            field=models.CharField(max_length=150, verbose_name='Bajada noticia(obligatorio)'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='public',
            field=models.BooleanField(default=True, verbose_name='publico'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo_noticia',
            field=models.CharField(max_length=150, unique=True, verbose_name='Titulo Noticia (obligatorio)'),
        ),
    ]
