# Generated by Django 4.2.2 on 2023-07-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiasymedia', '0004_noticias_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='slug',
            field=models.SlugField(default='video', editable=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='tag',
            field=models.ManyToManyField(to='noticiasymedia.tag', verbose_name='Tag Multimedia'),
        ),
    ]
