# Generated by Django 4.2.2 on 2024-06-28 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regioncomuna', '0003_cargar_datos_regioncomuna'),
        ('noticiasymedia', '0005_multimedia_slug_alter_multimedia_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo_album', models.CharField(max_length=200, unique=True, verbose_name='Titulo Album (obligatorio)')),
                ('descripcion_album', models.CharField(max_length=500, verbose_name='Descripcion Album (obligatorio)')),
                ('foto_portada', imagekit.models.fields.ProcessedImageField(null=True, upload_to='album', verbose_name='Foto Portada (obligatorio)')),
                ('slug', models.SlugField(editable=False, max_length=300)),
                ('public', models.BooleanField(default=True, verbose_name='publico')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.region', verbose_name='Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('foto', imagekit.models.fields.ProcessedImageField(null=True, upload_to='album', verbose_name='Foto (obligatorio)')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion Foto (obligatorio)')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticiasymedia.photoalbum', verbose_name='Album')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
