# Generated by Django 4.2.2 on 2024-06-28 22:35

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0003_cargar_datos_regioncomuna'),
        ('noticiasymedia', '0006_photoalbum_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Álbum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='foto_portada',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='album_photos', verbose_name='Foto Portada (obligatorio)'),
        ),
        migrations.AlterUniqueTogether(
            name='photoalbum',
            unique_together={('region', 'date')},
        ),
    ]
