# Generated by Django 4.2.2 on 2024-07-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regioncomuna', '0003_cargar_datos_regioncomuna'),
        ('noticiasymedia', '0008_alter_photoalbum_options_remove_photoalbum_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoalbum',
            name='date',
            field=models.DateField(verbose_name='Fecha del Álbum (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regioncomuna.region', verbose_name='Region (obligatorio)'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='titulo_album',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titulo Album'),
        ),
    ]
