# Generated by Django 4.2.2 on 2024-07-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticiasymedia', '0010_alter_photo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion Foto (opcional)'),
        ),
    ]
