# Generated by Django 4.2.2 on 2023-07-06 22:17

import applications.home.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_preguntasfrecuentes_tipodocumentos_secciondocumentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='titulo_documento',
            field=models.CharField(default='Cualquiera', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='project_documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.home.functions.validate_file_size_five]),
        ),
    ]
