# Generated by Django 4.2.2 on 2023-07-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documentos_titulo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasfrecuentes',
            name='pregunta_frecuente',
            field=models.CharField(max_length=400),
        ),
    ]
