# Generated by Django 4.2.2 on 2023-07-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_secciondocumentos_seccion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='titulo_documento',
            field=models.CharField(max_length=200),
        ),
    ]
