# Generated by Django 4.2.2 on 2023-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_countdown_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdown',
            name='start_date',
            field=models.DateField(),
        ),
    ]
