# Generated by Django 4.2.2 on 2023-07-14 14:41

import applications.home.functions
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_countdown_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Solo se permiten archivos PDF.'), applications.home.functions.validate_file_size_twenty]),
        ),
    ]
