# Generated by Django 4.2.2 on 2024-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_consejoasesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consejoasesor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
