# Generated by Django 4.2.2 on 2023-07-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_comuna_user_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
