# Generated by Django 4.2.2 on 2023-07-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEM', 'Femenino'), ('MASC', 'Masculino'), ('NOBIN', 'No binarie'), ('PND', 'Prefiero no decirlo')], max_length=5, null=True),
        ),
    ]
