# Generated by Django 4.2.2 on 2023-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='politica_privacidad',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
