# Generated by Django 4.2.2 on 2023-07-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_politica_privacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encuesta_completada',
            field=models.BooleanField(default=False),
        ),
    ]
