# Generated by Django 4.2.2 on 2023-07-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_encuesta_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recibir_resultados',
            field=models.BooleanField(default=False),
        ),
    ]
