# Generated by Django 4.2.2 on 2023-07-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_recibir_resultados'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pueblos_originarios',
            field=models.CharField(blank=True, choices=[('NP', 'No pertenece'), ('AIM', 'Aimara'), ('ATAC', 'Atacameño o Lickanantay'), ('COLL', 'Colla'), ('CHAN', 'Chango'), ('DIAG', 'Diaguita'), ('KAW', 'Kawésqar'), ('MAPU', 'Mapuche'), ('QUEC', 'Quechua'), ('RAPA', 'Rapa-Nui'), ('YAG', 'Yagán'), ('OTRO', 'Otro')], max_length=5, null=True),
        ),
    ]
