# Generated by Django 4.2.2 on 2023-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_pueblos_originarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pueblos_originarios',
            new_name='pueblo_originario',
        ),
    ]
