# Generated by Django 4.2.2 on 2023-07-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_genero_alter_user_pueblo_originario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Elige una opción'), ('FEM', 'Femenino'), ('MASC', 'Masculino'), ('TRMAS', 'Transmasculino'), ('TRFEM', 'Transfemenino'), ('NOBIN', 'No binario'), ('OTRO', 'Otro'), ('PND', 'Prefiero no decirlo')], max_length=5, null=True),
        ),
    ]
