# Generated by Django 4.2.2 on 2024-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='familiaridad',
            field=models.CharField(blank=True, choices=[('', 'Elige una opción'), ('14-18', 'De 14 a 18 años'), ('19-25', 'De 19 a 25 años'), ('26-35', 'De 26 a 35 años'), ('36-45', 'De 36 a 45 años'), ('46-55', 'De 46 a 55 años'), ('56-65', 'De 56 a 65 años'), ('66-75', 'De 66 a 75 años'), ('75-120', '76 años o más')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.CharField(blank=True, choices=[('', 'Elige una opción'), ('14-18', 'De 14 a 18 años'), ('19-25', 'De 19 a 25 años'), ('26-35', 'De 26 a 35 años'), ('36-45', 'De 36 a 45 años'), ('46-55', 'De 46 a 55 años'), ('56-65', 'De 56 a 65 años'), ('66-75', 'De 66 a 75 años'), ('75-120', '76 años o más')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='genero',
            field=models.CharField(blank=True, choices=[('', 'Elige una opción'), ('FEM', 'Femenino'), ('MASC', 'Masculino'), ('NOBIN', 'No binario'), ('OTRO', 'Otro'), ('PND', 'Prefiero no decirlo')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pueblo_originario',
            field=models.CharField(blank=True, choices=[('', 'Elige una opción'), ('NP', 'No pertenece'), ('AIM', 'Aimara'), ('ATAC', 'Atacameño'), ('COLL', 'Colla'), ('CHAN', 'Chango'), ('DIAG', 'Diaguita'), ('KAW', 'Kawésqar'), ('MAPU', 'Mapuche'), ('QUEC', 'Quechua'), ('RAPA', 'Rapa-Nui'), ('SELK', 'Selknam'), ('YAG', 'Yagán'), ('OTRO', 'Otro')], max_length=5, null=True),
        ),
    ]
