# Generated by Django 4.2.2 on 2024-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_familiaridad_alter_user_edad_alter_user_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='familiaridad',
            field=models.CharField(blank=True, choices=[('si', 'Si'), ('no', 'No')], null=True),
        ),
    ]
