# Generated by Django 4.2.2 on 2023-06-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_respuesta_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntados',
            name='prioridad_1',
        ),
        migrations.RemoveField(
            model_name='preguntados',
            name='prioridad_2',
        ),
        migrations.RemoveField(
            model_name='preguntados',
            name='prioridad_3',
        ),
        migrations.RemoveField(
            model_name='preguntados',
            name='prioridad_4',
        ),
        migrations.AddField(
            model_name='preguntados',
            name='propuesta_1',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], default=1, help_text='La descentralización permite tomar decisiones, a partir de las características, conocimientos y experiencias de los territorios y sus comunidades.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntados',
            name='propuesta_2',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], default=1, help_text='La descentralización permite fortalecer la democracia a nivel de regiones y comunas.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntados',
            name='propuesta_3',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], default=1, help_text='La descentralización permite satisfacer necesidades de manera oportuna y eficiente.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntados',
            name='propuesta_4',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], default=1, help_text='La descentralización permite disminuir las desigualdades sociales y territoriales.'),
            preserve_default=False,
        ),
    ]
