# Generated by Django 4.2.2 on 2023-06-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_preguntados_prioridad_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntatres',
            name='prioridad_1',
        ),
        migrations.RemoveField(
            model_name='preguntatres',
            name='prioridad_2',
        ),
        migrations.RemoveField(
            model_name='preguntatres',
            name='prioridad_3',
        ),
        migrations.RemoveField(
            model_name='preguntatres',
            name='prioridad_4',
        ),
        migrations.RemoveField(
            model_name='preguntatres',
            name='prioridad_5',
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='iniciativa_1',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], default=1, help_text='Establecer mecanismos de participación ciudadana y rendición de cuentas.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='iniciativa_2',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], default=1, help_text='Establecer qué le corresponde institucionalmente realizar a los distintos niveles de la administración pública, nacional, regional y comunal.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='iniciativa_3',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], default=1, help_text='Garantizar la autonomía y el buen uso de los recursos financieros públicos.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='iniciativa_4',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], default=1, help_text='Coordinar a distintos actores públicos, privados y sociales, para la mejor obtención de objetivos de desarrollo.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='iniciativa_5',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], default=1, help_text='Fortalecer capacidades técnicas y profesionales en comunas y regiones, para generar mayores oportunidades de desarrollo económico, social y cultural.'),
            preserve_default=False,
        ),
    ]
