# Generated by Django 4.2.2 on 2023-06-28 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0004_remove_preguntatres_prioridad_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntacinco',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntados',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntatres',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preguntauno',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='preguntacinco',
            unique_together={('usuario',)},
        ),
        migrations.AlterUniqueTogether(
            name='preguntados',
            unique_together={('usuario',)},
        ),
        migrations.AlterUniqueTogether(
            name='preguntatres',
            unique_together={('usuario',)},
        ),
        migrations.AlterUniqueTogether(
            name='preguntauno',
            unique_together={('usuario',)},
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
