# Generated by Django 4.2.2 on 2023-06-29 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_preguntacinco_usuario_preguntados_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntacinco',
            name='texto_respuesta',
            field=models.TextField(blank=True),
        ),
    ]
