# Generated by Django 4.2.2 on 2023-07-02 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0006_alter_preguntacinco_texto_respuesta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntacinco',
            options={'verbose_name': 'Pregunta 5: ¿Qué tema, iniciativa o aspecto profundizaría o agregaría, considerando el vínculo entre descentralización y su vida personal y en comunidad?'},
        ),
        migrations.AlterModelOptions(
            name='preguntados',
            options={'verbose_name': 'Pregunta 2: Impacto de la descentralización en las personas y comunidades.'},
        ),
        migrations.AlterModelOptions(
            name='preguntatres',
            options={'verbose_name': 'Pregunta 3: Iniciativas que podrían ser incluidas dentro de la Política Nacional de Descentralización.'},
        ),
        migrations.AlterModelOptions(
            name='preguntauno',
            options={'verbose_name': 'Pregunta 1: ¿Qué valor le otorga usted a la descentralización en la cotidianeidad y en la calidad de vida de las personas?'},
        ),
        migrations.AlterField(
            model_name='preguntacinco',
            name='texto_respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PreguntaCuatro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tematica_1', models.IntegerField(choices=[(1, 'Muy importante'), (2, 'Importante'), (3, 'Poco importante'), (4, 'No es importante'), (5, 'No sabría responder')], help_text='las medidas deben considerar de manera transversal la perspectiva de género, entendida como una mirada destinada a hacer que las preocupaciones y experiencias de las mujeres, así como las de los hombres y de las diversidades sexo genéricas, sean un elemento integrante de la elaboración de la Política.', verbose_name='Enfoque de género')),
                ('tematica_2', models.IntegerField(choices=[(1, 'Muy importante'), (2, 'Importante'), (3, 'Poco importante'), (4, 'No es importante'), (5, 'No sabría responder')], help_text='las medidas deben considerar e integrar el respeto a la diversidad territorial en cuanto a las características identitarias de los territorios, su historia, sus características económicas, sociales y culturales, entre otras.', verbose_name='Diversidad territorial')),
                ('tematica_3', models.IntegerField(choices=[(1, 'Muy importante'), (2, 'Importante'), (3, 'Poco importante'), (4, 'No es importante'), (5, 'No sabría responder')], help_text='las medidas y acciones deben promover la participación activa de la sociedad civil en las decisiones de los territorios.', verbose_name='Participación ciudadana')),
                ('tematica_4', models.IntegerField(choices=[(1, 'Muy importante'), (2, 'Importante'), (3, 'Poco importante'), (4, 'No es importante'), (5, 'No sabría responder')], help_text='las medidas deben considerar capacidades técnicas y profesionales para enfrentar los desafíos de desarrollo económico, social y cultural.', verbose_name='Capital humano territorial')),
                ('tematica_5', models.IntegerField(choices=[(1, 'Muy importante'), (2, 'Importante'), (3, 'Poco importante'), (4, 'No es importante'), (5, 'No sabría responder')], help_text='las medidas deben minimizar su impacto negativo sobre el medio ambiente.', verbose_name='Protección del medioambiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '¿Qué tan importante es incluir las siguientes temáticas de forma transversal en la Política Nacional de Descentralización?',
                'unique_together': {('usuario',)},
            },
        ),
    ]
