# Generated by Django 4.2.2 on 2023-07-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_preguntacinco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntacuatro',
            options={'verbose_name': 'Pregunta 4: ¿Qué tan importante es incluir las siguientes temáticas de forma transversal en la Política Nacional de Descentralización?'},
        ),
    ]
