# Generated by Django 4.2.2 on 2023-07-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_preguntacuatro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntauno',
            name='valor',
            field=models.CharField(choices=[('1', 'Es muy importante'), ('2', 'Es importante'), ('3', 'Es poco importante'), ('4', 'No es importante'), ('5', 'No sabría responder')], max_length=1, verbose_name='Valor'),
        ),
    ]
