# Generated by Django 4.2.2 on 2023-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_preguntauno_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_1',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], help_text='Permite tomar decisiones, a partir de las características, conocimientos y experiencias de los territorios y sus comunidades.'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_2',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], help_text='Fortalece la democracia a nivel de regiones y comunas.'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_3',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], help_text='Permite satisfacer necesidades de manera oportuna y eficiente.'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_4',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4')], help_text='Disminuye las desigualdades sociales y territoriales.'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_1',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], help_text='Definir las tareas de la administración pública a nivel nacional, regional y comunal.'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_2',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], help_text='Fortalecer habilidades técnicas y profesionales en comunas y regiones para impulsar el desarrollo económico, social y cultural.'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_3',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], help_text='Establecer mecanismos de participación ciudadana y rendición de cuentas.'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_4',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], help_text='Garantizar la autonomía y el buen uso de los recursos financieros públicos.'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_5',
            field=models.IntegerField(choices=[(1, 'Prioridad 1'), (2, 'Prioridad 2'), (3, 'Prioridad 3'), (4, 'Prioridad 4'), (5, 'Prioridad 5')], help_text='Coordinar a distintos actores públicos, privados y sociales, para la mejor obtención de objetivos de desarrollo.'),
        ),
    ]
