# Generated by Django 4.2.2 on 2024-05-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_alter_preguntacinco_texto_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntauno',
            name='valor',
            field=models.CharField(choices=[('1', 'Es muy importante'), ('2', 'Es importante'), ('3', 'Es algo importante'), ('4', 'No es importante'), ('5', 'No sabría responder')], max_length=1, verbose_name='Valor'),
        ),
    ]
