# Generated by Django 4.2.2 on 2024-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_alter_preguntauno_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_1',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que las autoridades elegidas directamente y por sufragio universal, rindan cuenta a la ciudadanía.', verbose_name='Rendimiento de cuentas'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_2',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que la ciudadanía tenga acceso a bienes y prestación de servicios públicos, por parte de los gobiernos regionales y municipalidades.', verbose_name='Acceso a bienes y prestación de servicios'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_3',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que los gobiernos regionales y municipalidades cuenten con mayores recursos financieros, y sus usos sean definidos en el territorio.', verbose_name='Mayores recursos públicos'),
        ),
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_4',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que los gobiernos regionales y municipalidades cuenten con más profesionales, para el cumplimiento de sus objetivos.', verbose_name='Más profesionales,'),
        ),
        migrations.AlterField(
            model_name='preguntauno',
            name='valor',
            field=models.CharField(choices=[('1', 'No es importante'), ('2', 'Algo importante'), ('3', 'Importante'), ('4', 'Muy importante'), ('5', 'No sabría responder')], max_length=1, verbose_name='Valor'),
        ),
    ]
