# Generated by Django 4.2.2 on 2024-05-16 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0015_alter_preguntatres_iniciativa_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntacuatro',
            name='tematica_1',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Promueve la honradez, integridad y rectitud en el actuar de las autoridades, como asimismo el acceso de información a la comunidad.', verbose_name='Probidad y transparencia:'),
        ),
        migrations.AlterField(
            model_name='preguntacuatro',
            name='tematica_2',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Fomenta la implicación directa y activa de la sociedad civil en los asuntos públicos.', verbose_name='Participación ciudadana:'),
        ),
        migrations.AlterField(
            model_name='preguntacuatro',
            name='tematica_3',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Reconoce la capacidad de los gobiernos regionales y las municipalidades en la elección de sus autoridades, la administración de sus recursos, y en el ejercicio de sus funciones, atribuciones y facultades normativas.', verbose_name='Autonomía:'),
        ),
        migrations.AlterField(
            model_name='preguntacuatro',
            name='tematica_4',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Garantiza que todas las personas tengan igualdad de oportunidades, sin importar su grupo étnico, país de procedencia, orientación sexual, raza, habilidad, género, edad o incluso intereses personales.', verbose_name='Diversidad e inclusión:'),
        ),
        migrations.AlterField(
            model_name='preguntacuatro',
            name='tematica_5',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Garantiza que mujeres, hombres, niñas y niños gocen, por igual, de los mismos derechos, recursos, oportunidades y protecciones.', verbose_name='Igualdad de género:'),
        ),
        migrations.CreateModel(
            name='PreguntaSiete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta 7: ¿Qué tema, iniciativa o aspecto profundizaría o agregaría, considerando el vínculo entre descentralización y su vida personal y en comunidad?',
                'unique_together': {('usuario',)},
            },
        ),
        migrations.CreateModel(
            name='PreguntaSeis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(choices=[('1', 'No es importante'), ('2', 'Algo importante'), ('3', 'Importante'), ('4', 'Muy importante'), ('5', 'No sabría responder')], max_length=1, verbose_name='Valor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PREGUNTA SEIS Pregunta 1: ¿Qué valor le otorga usted a la descentralización en la cotidianeidad y en la calidad de vida de las personas?',
                'unique_together': {('usuario',)},
            },
        ),
    ]
