# Generated by Django 4.2.2 on 2024-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0016_alter_preguntacuatro_tematica_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preguntaseis',
            options={'verbose_name': 'Considerando que una Política de Descentralización de Chile contaría con una agenda de trabajo con un plazo de implementación a 10 años, ¿con cuál de las siguientes alternativas usted está más de acuerdo?'},
        ),
        migrations.AlterModelOptions(
            name='preguntasiete',
            options={'verbose_name': 'Para finalizar y considerando sus respuestas anteriores, ¿qué temática o medida agregaría, para serconsiderada en una Política de Descentralización de Chile? Esta pregunta es opcional.'},
        ),
        migrations.AlterField(
            model_name='preguntaseis',
            name='valor',
            field=models.CharField(choices=[('1', 'Mejorará la calidad de vida de las personas.'), ('2', 'Mantendrá de igual manera la calidad de vida de las personas.'), ('3', 'Generará un retroceso en la calidad de vida de las personas.'), ('4', 'No sabría responder')], max_length=1, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='preguntasiete',
            name='texto_respuesta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
