# Generated by Django 4.2.2 on 2024-05-29 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_alter_preguntaseis_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntacinco',
            name='texto_respuesta',
        ),
        migrations.AddField(
            model_name='preguntacinco',
            name='opciones',
            field=models.CharField(choices=[(1, 'Opción 1'), (1, 'Opción 2'), (1, 'Opción 3')], default=django.utils.timezone.now, max_length=2000, verbose_name='Selecciona tres opciones'),
            preserve_default=False,
        ),
    ]
