# Generated by Django 4.2.2 on 2024-05-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_remove_preguntacinco_texto_respuesta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntacinco',
            name='opciones',
            field=models.CharField(choices=[(1, 'Opción 1'), (2, 'Opción 2'), (3, 'Opción 3')], max_length=2000, verbose_name='Selecciona tres opciones'),
        ),
    ]
