# Generated by Django 4.2.2 on 2024-05-31 22:16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0022_alter_preguntacinco_opciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionesPreguntaCinco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=2)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='preguntacinco',
            name='opciones',
        ),
        migrations.AddField(
            model_name='preguntacinco',
            name='opciones',
            field=models.ManyToManyField(to='surveys.opcionespreguntacinco', verbose_name='Selecciona tres opciones'),
        ),
    ]
