# Generated by Django 4.2.2 on 2024-06-13 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0025_alter_preguntatres_iniciativa_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreguntaCuatro',
        ),
    ]
