# Generated by Django 4.2.2 on 2024-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0027_alter_preguntados_propuesta_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_2',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que la ciudadanía tenga acceso a bienes y prestaciones de servicios públicos, a través de los gobiernos regionales y municipalidades.', verbose_name='Acceso a bienes y prestación de servicios'),
        ),
    ]
