# Generated by Django 4.2.2 on 2024-06-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0028_alter_preguntados_propuesta_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntados',
            name='propuesta_2',
            field=models.IntegerField(choices=[(1, '1: Poco prioritario'), (2, '2: Algo prioritario'), (3, '3: Prioritario'), (4, '4: Muy prioritario'), (5, 'No sabría responder')], help_text='Que la ciudadanía tenga acceso a bienes y prestaciones de servicios públicos, que hoy entrega el gobierno central, a través de los gobiernos regionales y municipalidades.', verbose_name='Acceso a bienes y prestación de servicios'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_1',
            field=models.IntegerField(choices=[(1, 'Gobierno Regional'), (2, 'Municipalidad'), (3, 'Ambas'), (4, 'No sabría responder')], help_text='Iniciativas ambientales', verbose_name='Iniciativas ambientales'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_2',
            field=models.IntegerField(choices=[(1, 'Gobierno Regional'), (2, 'Municipalidad'), (3, 'Ambas'), (4, 'No sabría responder')], help_text='Infraestructura pública', verbose_name='Infraestructura pública'),
        ),
        migrations.AlterField(
            model_name='preguntatres',
            name='iniciativa_4',
            field=models.IntegerField(choices=[(1, 'Gobierno Regional'), (2, 'Municipalidad'), (3, 'Ambas'), (4, 'No sabría responder')], help_text='Fomento productivo', verbose_name='Fomento productivo'),
        ),
    ]
